def label = "build"
podTemplate(label: label, yaml: """
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: build
spec:
  containers:
  - name: build
    image: kapil0123/jenkins-build-agent:1.0
    command:
    - cat
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
"""
) {
    node (label) {

        stage ('Checkout SCM'){
          git url: 'https://kapilhsr@bitbucket.org/kapilhsr/kapil-edweb-login-integration.git', branch: 'master'
          container('build') {
                stage('Build a Maven project') {
                    sh '/opt/maven/bin/mvn clean deploy -s settings.xml'             
                }
            }
        }

        stage ('Docker Build'){
          container('build') {
                stage('Build Image') {
                    docker.withRegistry( 'https://registry.hub.docker.com', 'docker' ) {
                    def customImage = docker.build("kapil0123/webapp")
                    customImage.push()             
                    }
                }
            }
        }

        stage ('Helm Chart') {
          container('build') {
            dir('charts') {
              withCredentials([usernamePassword(credentialsId: 'jfrog', usernameVariable: 'username', passwordVariable: 'password')]) {
              sh 'ls -l'
              sh '/usr/local/bin/helm package webapp'
              sh '/usr/local/bin/helm push-artifactory webapp-1.0.tgz https://sharedevops.jfrog.io/artifactory/dptweb-helm-local --username $username --password $password'
              }
            }
        }
        }
    }
}