apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-ebs-pv
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zones: us-east-1b # should match with where your nodes are else it will show something like
  # 0/2 nodes are available: 2 node(s) had volume node affinity conflict