pipeline {
  agent any

  stages {
      stage('SCM-Checkout') {
          steps {
              git branch: 'dev',
                  credentialsId: 'my_repo_creds',
                  url: 'https://myrepo@bitbucket.org/somefolder.git'
          }
      }
        stage('Docker build') {
            steps {
                dir("./folder/src/amf/build/") {
                    sh './build_docker.sh'
                }
              
          }
      }

  }
}
