# Deploy LoadBalancer services
apiVersion: v1
kind: Service
metadata:
  name: my-lb-service
  labels:
    app: httpd-app

spec:
  selector:
    app: login
    env: dev

  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
