# Deploy Nginx application with Liveness and Readiness Probe
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-container
        image: docker.io/nginx:1.18
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80 # if it fails it will be visible in log else not
        livenessProbe:
          tcpSocket:
            port: 80 # if it fails it will be visible in log else not